name: "Continuous Integration"

on:
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  style-check:
    name: Style check
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: true
    steps:
      - name: Checkout MMTk Ruby binding
        uses: actions/checkout@v3
        with:
          path: ./git/mmtk-ruby
      - name: Setup environment
        run: ./.github/scripts/ci-setup.sh
        working-directory: ./git/mmtk-ruby
      - name: Style checks
        run: ./.github/scripts/ci-style.sh
        working-directory: ./git/mmtk-ruby

  build-and-test:
    name: Build and test
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: true
      matrix:
        debug-level: ["debug", "release"]
    env:
      DEBUG_LEVEL: ${{ matrix.debug-level }}
    steps:
      - name: Checkout MMTk Ruby binding
        uses: actions/checkout@v3
        with:
          path: ./git/mmtk-ruby

      - name: Determine Ruby repository and revision
        id: extract-ruby-revision
        run: python ./.github/scripts/extract-ruby-revision.py ./mmtk/Cargo.toml --github-output=$GITHUB_OUTPUT

      - name: Checkout Ruby
        uses: actions/checkout@v3
        with:
          repository: ${{ steps.extract-ruby-revision.outputs.ruby_repo }}
          ref: ${{ steps.extract-ruby-revision.outputs.ruby_rev }}
          path: ./git/ruby

      - name: Setup environment
        run: ./.github/scripts/ci-setup.sh
        working-directory: ./git/mmtk-ruby

      - name: Build MMTk Ruby ${{ matrix.debug-level }}
        run: ./.github/scripts/ci-build.sh
        working-directory: ./git/mmtk-ruby

      - name: Run bootstrap tests (btest)
        run: ./.github/scripts/ci-btest.sh
        working-directory: ./git/mmtk-ruby

      - name: Run all tests (test-all)
        run: ./.github/scripts/ci-test-all.sh
        working-directory: ./git/mmtk-ruby
